version: '3'
services:
  php-apache:
    build:
      context: './php-apache'
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:z
    links:
      - 'mysql'
    environment:
      - VIRTUAL_HOST=legacy.localdev,portal.legacy.localdev,staff.legacy.localdev
  mysql:
    container_name: "mysqldb"
    build:
      context: './mysql'
    ports:
      - 3308:3306
    volumes:
      - ~/mysql:/var/lib/mysql
    environment:
      TZ: "Europe/Copenhagen"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_USER: 'legacygame'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - 'mysql'
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PMA_PORTS=3306
      - UPLOAD_LIMIT=2G
      - PMA_HOSTS=mysqldb

volumes:
  mysql: