version: '3'
services:
  php-apache:
    build:
      context: './php-apache'
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:z
    environment:
      - VIRTUAL_HOST=legacy.localdev,portal.legacy.localdev,staff.legacy.localdev
    networks:
      - legacy-game-net
  mysql:
    platform: linux/x86_64
    container_name: "mysqldb"
    build:
      context: './mysql'
    ports:
      - 3308:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      TZ: "UTC"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_USER: 'legacygame'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - legacy-game-net
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PMA_HOSTS=mysqldb
      - PMA_PORTS=3306
      - MYSQL_ROOT_PASSWORD=password
      #- PMA_ARBITRARY=1
      - UPLOAD_LIMIT=2G
    networks:
      - legacy-game-net

networks:
  legacy-game-net:
    driver: bridge

volumes:
  mysql:
