services:
  php-apache:
    restart: always
    build:
      context: './php-apache'
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:z
    environment:
      - VIRTUAL_HOST=legacy.localdev,portal.legacy.localdev,staff.legacy.localdev
    networks:
      - legacy-game-net
  mariadb:
    image: mariadb:11.3
    restart: always
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - legacy-game-net
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8080:80
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PMA_HOSTS=mariadb
      - PMA_PORTS=3306
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
      #- PMA_ARBITRARY=1
      - UPLOAD_LIMIT=2G
    networks:
      - legacy-game-net

networks:
  legacy-game-net:
    driver: bridge

volumes:
  mariadb:
